remote_theme: just-the-docs/just-the-docs
title: Archive Box Database
description: Graduate database design project

search_enabled: true
nav_enabled: true


# Footer content
footer_content: "Created by Kelsey Kiantoro | Graduate Database Design Project (Fall 2024) | Built with Just the Docs"
