theme: jekyll-theme-cayman
title: Archive Box Management Database
description: Graduate database design project - Relational database design and implementation

# Enable search
search_enabled: true

# Navigation
nav_enabled: true
